parameter study grid search

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = [11,12,13]
c = [21,22]

In [3]:
m= np.repeat(a, len(b)*len(c))
x = np.tile(m, 1)
m, x

(array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 4]),
 array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 4]))

In [4]:
#m = np.tile(b, 4)
m = np.repeat(b, len(c))
y = np.tile(m, len(a))
m, y

(array([11, 11, 12, 12, 13, 13]),
 array([11, 11, 12, 12, 13, 13, 11, 11, 12, 12, 13, 13, 11, 11, 12, 12, 13,
        13, 11, 11, 12, 12, 13, 13]))

In [5]:
m= np.repeat(c, 1)
z = np.tile(m, len(a)*len(b))
m, z

(array([21, 22]),
 array([21, 22, 21, 22, 21, 22, 21, 22, 21, 22, 21, 22, 21, 22, 21, 22, 21,
        22, 21, 22, 21, 22, 21, 22]))

In [6]:
x, y, z

(array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 4]),
 array([11, 11, 12, 12, 13, 13, 11, 11, 12, 12, 13, 13, 11, 11, 12, 12, 13,
        13, 11, 11, 12, 12, 13, 13]),
 array([21, 22, 21, 22, 21, 22, 21, 22, 21, 22, 21, 22, 21, 22, 21, 22, 21,
        22, 21, 22, 21, 22, 21, 22]))

In [7]:
#a = [1,2,3,4]
#b = [21,22]
#c = [31,32,33]
arrs = [a, b, c]
arr_len = []
for arr in arrs:
    arr_len.append(len(arr))
for ii, arr in enumerate(arrs):
    print(arr_len[slice(0,ii)], arr_len[slice(ii+1,None)])
    print(np.prod(arr_len[slice(0,ii)]), np.prod(arr_len[slice(ii+1,None)]))
#for ii, arr in enumerate(arrs):
#    print(arr_len[slice(ii,None)])
arr_len

[] [3, 2]
1.0 6
[4] [2]
4 2
[4, 3] []
12 1.0


[4, 3, 2]

In [8]:
def parameter_study(*arrs):
    arr_len = []
    for arr in arrs:
        arr_len.append(len(arr))
    for ii, arr in enumerate(arrs):
        if ii==0:
            continue
    pass

In [9]:
r_pipe_soil = np.array([0.6, 0.7,0.8,0.9])
phi_seabed = np.array([20.0, 30.0, 41.0, 44.0])